modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/daniel-goossens/Chisels-and-Bits2/issues"

[[mods]]
modId="chiselsandbits2"
version="${file.jarVersion}"
displayName="Chisels & Bits 2"
# updateJSONURL=""
# displayURL=""
logoFile="chiselsandbits2.png"
credits="Original mod created by AlgorithmX2"
authors="Aeltumn, AlgorithmX2"
description='''
The successor to the original Chisels and Bits mod for minecraft 1.12. A mod about sculpting, decorating and aesthetics.
'''
[[dependencies.chiselsandbits2]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.39,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.chiselsandbits2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

# Soft dependency on JEI versions 6.0.0.10 or newer for mc 1.14
[[dependencies.chiselsandbits2]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.11,)"
    ordering="BEFORE"
    side="BOTH"
